server:
  port: 8443
  servlet:
    context-path: /idp    
  ssl:
    enabled: true
    key-store: classpath:ssl.jks
    key-store-type: JKS
    key-alias: local
    key-store-password: secret
    key-password: secret
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    
spring:
  messages:
    basename: messages,idp-errors/idp-error-messages

demo:
  users:
  - personal-number: 188803099368
    date-of-birth: 1888-03-09
    given-name: Agda
    surname: Andersson
    display-name: Agda Andersson
  - personal-number: 197609265819
    date-of-birth: 1976-09-26
    given-name: Alrik
    surname: Lidén
    display-name: Alrik Lidén
  - personal-number: 197705232382
    date-of-birth: 1977-05-23
    given-name: Frida
    surname: Kranstege
    display-name: Frida Kranstege
        
saml:
  idp:
    entity-id: https://demo.swedenconnect.se/idp
    base-url: https://local.dev.swedenconnect.se:8443/idp    
    credentials:
      sign:
        resource: classpath:idp-credentials.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:idp-credentials.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:idp-credentials.jks
        alias: metadata
        password: secret
        type: JKS
    endpoints:
      metadata: /saml2/metadata
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: target/metadata-backup.xml
      validation-certificate: classpath:sandbox-metadata.crt
        
logging:
  level:
    se:
      swedenconnect:
        spring:
          saml: TRACE
        

